export const playercols = [
    {
      key: "name",
      label: "NAME",
    },
    {
      key: "role",
      label: "ROLE",
    },
    {
      key: "title",
      label: "Title",
    },
    {
      key: "status",
      label: "STATUS",
      },
  ];
 export const playerrows = [
    {
      key: "1",
      name: "Avweri",
      role: "Player",
      title: "",
      status: "Active",
    },
    {
      key: "2",
      name: "CloverPetal",
      role: "Player",
      title: "",
      status: "Active",
    },
    {
      key: "3",
      name: "madzvie",
      role: "Player",
      title: "",
      status: "Active",
    },
    {
      key: "4",
      name: "GroceryCart",
      role: "Player",
      title: "Basket on Wheels",
      status: "Active",
    },
    {
        key: "5",
        name: "WaldoAndFriends",
        role: "Player",
        title: "Friends Still Looking for Him",
        status: "Active",
    },
    {
        key: "6",
        name: "Zevira",
        role: "Player",
        title: "",
        status: "Active",
    },
    {
        key: "7",
        name: "Nathans_Cookie",
        role: "Player",
        title: "Has Cookies",
        status: "Active",
    },
    {
        key: "8",
        name: "Warden_InDark",
        role: "Player",
        title: "",
        status: "Active",
    },
    {
        key: "9",
        name: "Grad",
        role: "Player",
        title: "",
        status: "Active",
    },
    {
        key: "10",
        name: "GoWMan",
        role: "Admin",
        title: "Alien Waifu",
        status: "Active",
    },
    {
        key: "11",
        name: "ConfuzzedCat",
        role: "Player",
        title: "Only Slightly Confuzzed",
        status: "Active",
    },
    {
        key: "12",
        name: "KK964",
        role: "Admin",
        title: "The Boss",
        status: "Active",
    },
    {
        key: "13",
        name: "greenbanana",
        role: "Admin",
        title: "Not Quite Ripe",
        status: "Active",
    },
    {
        key: "14",
        name: "Agil",
        role: "Admin",
        title: "",
        status: "Active",
    },
  ];