export const playercols = [
    {
      key: "name",
      label: "NAME",
    },
    {
      key: "role",
      label: "ROLE",
    },
    {
      key: "title",
      label: "TITLE",
    },
    {
      key: "status",
      label: "STATUS",
      },
      {
        key: "deaths",
        label: "DEATHS",
        },
  ];
 export const playerrows = [
    {
      key: "1",
      name: "Avweri",
      role: "Player",
      title: "Marco",
      status: "Active",
      deaths: "0",
    },
    {
      key: "2",
      name: "CloverPetal",
      role: "Player",
      title: "The Nicest",
      status: "Active",
      deaths: "0",
    },
    {
      key: "3",
      name: "Madzvie",
      role: "Player",
      title: "Vie Gang",
      status: "Active",
      deaths: "0",
    },
    {
      key: "4",
      name: "GroceryCart",
      role: "Player",
      title: "Basket on Wheels",
      status: "Active",
      deaths: "1",
    },
    {
        key: "5",
        name: "WaldoAndFriends",
        role: "Player",
        title: "Friends Still Looking for Him",
        status: "Active",
        deaths: "20",
    },
    {
        key: "6",
        name: "Zevira",
        role: "Player",
        title: "Zee",
        status: "Active",
        deaths: "1",
    },
    {
        key: "7",
        name: "Nathans_Cookie",
        role: "Player",
        title: "Has Cookies",
        status: "Active",
        deaths: "2",
    },
    {
        key: "8",
        name: "Warden_InDark",
        role: "Player",
        title: "Torchless",
        status: "Active",
        deaths: "0",
    },
    {
        key: "9",
        name: "Grad",
        role: "Player",
        title: "Doesn't Fail",
        status: "Active",
        deaths: "0",
    },
    {
        key: "10",
        name: "GoWMan",
        role: "Admin",
        title: "Alien Waifu",
        status: "Active",
        deaths: "0",
    },
    {
        key: "11",
        name: "ConfuzzedCat",
        role: "Player",
        title: "Only Slightly Confuzzed",
        status: "Active",
        deaths: "0",
    },
    {
        key: "12",
        name: "KK964",
        role: "Admin",
        title: "The Boss",
        status: "Active",
        deaths: "2",
    },
    {
        key: "13",
        name: "Greenbanana",
        role: "Admin",
        title: "Not Quite Ripe",
        status: "Active",
        deaths: "0",
    },
    {
        key: "14",
        name: "Agil",
        role: "Admin",
        title: "Babygirl Generator",
        status: "Active",
        deaths: "0",
    },
    {
      key: "15",
      name: "Elanulo",
      role: "Player",
      title: "Polo",
      status: "Active",
      deaths: "0",
   },
   {
    key: "16",
    name: "Dbest_",
    role: "Player",
    title: "The Best",
    status: "Active",
    deaths: "0",
    },
    {
      key: "17",
      name: "Jawunleashed",
      role: "Player",
      title: "Baby Shark",
      status: "Active",
      deaths: "0",
      },
      {
        key: "18",
        name: "Ish",
        role: "Player",
        title: "The Ish",
        status: "Active",
        deaths: "0",
        },
        {
          key: "19",
          name: "Perilous_Outlaw",
          role: "Player",
          title: "Pookie",
          status: "Active",
          deaths: "0",
          },
          {
            key: "20",
            name: "BoyJedi",
            role: "Player",
            title: "Not A Jedi",
            status: "Active",
            deaths: "0",
            },
            {
              key: "21",
              name: "Triogami",
              role: "Player",
              title: "Giga Chad",
              status: "Active",
              deaths: "0",
              },
              {
                key: "22",
                name: "Ricedneon",
                role: "Player",
                title: "Ricey",
                status: "Active",
                deaths: "0",
                },
  ];